project:
  type: website

website:
  title: ragnar
  site-url: https://dfalbel.github.io/py-ragnar/
  description: Retrieval-Augmented Generation (RAG) Workflows

  repo-url: https://github.com/dfalbel/py-ragnar
  repo-actions: [issue, edit]
  repo-subdir: docs

  page-footer:
    left: |
      Proudly supported by
      [![](https://posit.co/wp-content/uploads/2024/06/Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)

  navbar:
    search: true
      
    right:
      - text: Reference
        href: reference/index.qmd

      - icon: github
        href: https://github.com/dfalbel/py-ragnar
        aria-label: GitHub repository

quartodoc:
  package: ragnar
  render_interlinks: true
  sections:
    - title: Hello
      desc: Hello world
      contents:
        - HelloWorld